name       : mcomix
version    : 1.2.1
release    : 6
source     :
    - https://sourceforge.net/projects/mcomix/files/MComix-1.2.1/mcomix-1.2.1.tar.bz2/download : 7e43159dc585bc9bc31970a44bd2b4e42c303660c4c8cf7f0eda413a6f72fa3b
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : MComix is a user-friendly, customizable image viewer.
description: |
    MComix is a user-friendly, customizable image viewer.
builddeps  :
    - desktop-file-utils
    - python-gtk2
    - python-pillow
    - python-setuptools
    - xdg-utils
rundeps    :
    - p7zip
    - python-gobject2
    - python-gtk2
    - python-pillow
    - python-setuptools
    - unrar
setup      : |
    %patch -p1 < $pkgfiles/pil-image-version.patch
install    : |
    %python_install --single-version-externally-managed
    install -Dm00755 mime/comicthumb $installdir/usr/bin/comicthumb
    install -Dm00644 mime/comicthumb.1.gz $installdir/usr/share/man/man1/comicthumb.1.gz
    install -Dm00644 mime/comicthumb.thumbnailer $installdir/usr/share/thumbnailers/comicthumb.thumbnailer
