name       : mcomix
version    : 1.3.0
release    : 7
source     :
    - git|https://github.com/multiSnow/mcomix3.git : 483f4b3f2d9a125606d47597ae7eff3b38e5bf9d
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : MComix is a user-friendly, customizable image viewer.
description: |
    MComix is a user-friendly, customizable image viewer.
rundeps    :
    - p7zip
    - python3-cairo
    - python-gobject
    - python-pillow
    - unrar
install    : |
    python3 installer.py --target=$installdir/usr/lib/python%python3_version%/site-packages

    install -Dm00644 mime/mcomix.desktop $installdir/usr/share/applications/mcomix.desktop
    install -Dm00644 mime/mcomix.appdata.xml $installdir/usr/share/metainfo/mcomix.appdata.xml
    install -Dm00644 mime/comicthumb.thumbnailer $installdir/usr/share/thumbnailers/comicthumb.thumbnailer
    install -Dm00644 man/mcomix.1 $installdir/usr/share/man/man1/mcomix.1

    install -dm00755 $installdir/usr/bin
    ln -s /usr/lib/python%python3_version%/site-packages/mcomix/mcomixstarter.py $installdir/usr/bin/mcomix
    ln -s /usr/lib/python%python3_version%/site-packages/mcomix/comicthumb.py $installdir/usr/bin/comicthumb

    for size in 16x16 22x22 24x24 32x32 48x48; do
      install -dm00755 $installdir/usr/share/icons/hicolor/$size/apps/
      install -Dm00644 mcomix/mcomix/images/$size/mcomix.png $installdir/usr/share/icons/hicolor/$size/apps/mcomix.png
      install -Dm00644 mime/icons/$size/application-x-cb7.png $installdir/usr/share/icons/hicolor/$size/mimetypes/application-x-cb7.png
      install -Dm00644 mime/icons/$size/application-x-cbt.png $installdir/usr/share/icons/hicolor/$size/mimetypes/application-x-cbt.png
    done
