name       : mcomix
version    : 1.2.1
release    : 1
source     :
    - http://netassist.dl.sourceforge.net/project/mcomix/MComix-1.2.1/mcomix-1.2.1.tar.bz2 : 7e43159dc585bc9bc31970a44bd2b4e42c303660c4c8cf7f0eda413a6f72fa3b
license    : GPL-2.0
component  : office
summary    : MComix is a user-friendly, customizable image viewer.
description: |
    MComix is a user-friendly, customizable image viewer.
builddeps  :
    - pkgconfig(python-2.7)
    - desktop-file-utils
    - python-gtk2
    - python-pillow
    - python-setuptools
    - xdg-utils
rundeps    :
    - p7zip
    - python-gtk2
    - python-pillow
    - unrar
install    : |
    python setup.py install --root=%installroot% --no-compile -O0 --single-version-externally-managed
    install -Dm755 mime/comicthumb $installdir/usr/bin/comicthumb
    install -Dm644 mime/comicthumb.1.gz $installdir/usr/share/man/man1/comicthumb.1.gz
    install -Dm644 mime/comicthumb.thumbnailer $installdir/usr/share/thumbnailers/comicthumb.thumbnailer
